version: "3.8"
services:
  backend:
    image: "betulsahinn/loan-application-service:0.0.1-SNAPSHOT"
    ports:
      - "80:8080"
    restart: "always"
    environment:
      SPRING_PROFILES_ACTIVE: prod