spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/loan_application_data
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL10Dialect
  application:
    name: loan-application-service

server:
  port: 8080

twillo:
  account_sid: AC3b2d6a864cfff2d536d98de23b628fb7
  auth_token: 785ab55a79daab918ce080113762be92
  trial_number: +12015822294

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:9090/eureka