version: "3.8"
services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - 27017:27017
    volumes:
      - data:/data
    environment:
      - MONGO_INITDB_ROOT_USERNAME=rootuser
      - MONGO_INITDB_ROOT_PASSWORD=rootpass
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=rootuser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=rootpass
      - ME_CONFIG_MONGODB_SERVER=mongodb
  credit-score-service:
    image: betulsahinn/credit-score-service:0.0.1-SNAPSHOT
    restart: always
    ports:
      - 8082:8082
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://discover-server:9090/eureka/
      SPRING_DATA_MONGODB_HOST: mongodb
volumes:
  data: {}

networks:
  default:
    name: mongodb_network